# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-01 05:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('servico', '0003_auto_20170630_2344'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_venda', models.TextField(max_length=10)),
                ('data_venda', models.DateTimeField()),
                ('tipo', models.IntegerField(choices=[(1, 'A vista'), (2, 'Prazo')])),
                ('valor_venda', models.FloatField()),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('cod_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.Servico')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
            },
        ),
    ]
