# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 03:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_item', models.CharField(blank=True, max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cod_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.Servico')),
            ],
            options={
                'verbose_name_plural': 'itens',
                'verbose_name': 'item',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_venda', models.CharField(blank=True, max_length=10, unique=True)),
                ('data_venda', models.DateTimeField(auto_now=True)),
                ('tipo', models.IntegerField(choices=[(1, 'A vista'), (2, 'Prazo')], default=1)),
                ('valor_venda', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('servico', models.ManyToManyField(through='venda.ItensVenda', to='servico.Servico')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'vendas',
                'verbose_name': 'venda',
            },
        ),
        migrations.AddField(
            model_name='itensvenda',
            name='cod_venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.Venda'),
        ),
    ]
