# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-01 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
