# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_auto_20170827_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='servico',
            field=models.ManyToManyField(blank=True, through='venda.ItensVenda', to='servico.Servico'),
        ),
    ]
