# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0009_auto_20170904_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cod_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
    ]
