# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0010_auto_20170904_0138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-cod_venda'], 'verbose_name': 'venda', 'verbose_name_plural': 'vendas'},
        ),
    ]
