# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0011_auto_20170925_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'verbose_name': 'venda', 'verbose_name_plural': 'vendas'},
        ),
    ]
