# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0013_auto_20170926_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ('-valor_venda',), 'verbose_name': 'venda', 'verbose_name_plural': 'vendas'},
        ),
    ]
