# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0014_auto_20170926_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='comanda',
            field=models.BooleanField(default=True, verbose_name='Comanda Aberta'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'A vista'), (2, 'Prazo'), (3, 'Cartão')], default=1),
        ),
    ]
