# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0015_auto_20170926_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='desconto',
            field=models.IntegerField(blank=True, choices=[(0, 'Sem Desconto'), (1, '5%'), (2, '10%'), (3, '15%'), (4, '20%')], default=0),
        ),
    ]
