# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0016_venda_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='comanda',
            field=models.BooleanField(default=True, verbose_name='Comanda'),
        ),
    ]
