# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0017_auto_20170927_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3),
        ),
    ]
