# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0019_auto_20170927_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
