# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0020_venda_valor_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cod_venda',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
