# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 23:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0021_auto_20171002_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 3, 20, 36, 40, 388849)),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(),
        ),
    ]
