# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 00:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0022_auto_20171003_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 3, 21, 5, 11, 405551)),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
