# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 01:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0023_auto_20171003_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 7, 22, 20, 30, 58623)),
        ),
    ]
