# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 17:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0025_auto_20171008_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 8, 14, 44, 50, 973694)),
        ),
    ]
