# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 19:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venda', '0026_auto_20171008_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='itensvenda',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 8, 16, 29, 37, 497500)),
        ),
    ]
