# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0028_auto_20171012_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 14, 13, 41, 52, 234617)),
        ),
        migrations.AlterField(
            model_name='venda',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'A vista'), (2, 'Prazo'), (3, 'Debito'), (4, 'Credito')]),
        ),
    ]
