# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 05:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0029_auto_20171014_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 16, 2, 51, 30, 128502)),
        ),
    ]
