# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 04:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0031_auto_20171016_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensvenda',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 17, 1, 48, 20, 954905)),
        ),
    ]
