# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 05:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0032_auto_20171017_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 17, 2, 21, 55, 719080)),
        ),
        migrations.AlterField(
            model_name='venda',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'A vista'), (2, 'Prazo'), (3, 'Debito'), (4, 'Credito')]),
        ),
    ]
