# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 05:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0037_auto_20171017_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 17, 2, 43, 35, 773742)),
        ),
    ]
