# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 19:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0041_auto_20171017_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 17, 16, 26, 44, 455771)),
        ),
    ]
