# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0043_auto_20171017_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 18, 10, 8, 14, 574232)),
        ),
    ]
