# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 17:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0045_auto_20171018_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 21, 14, 14, 34, 161601)),
        ),
    ]
