# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 17:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0046_auto_20171021_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 21, 14, 23, 8, 555545)),
        ),
    ]
