# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 18:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0047_auto_20171021_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 21, 15, 31, 28, 841601)),
        ),
    ]
