# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 02:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0050_auto_20171022_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 22, 23, 44, 3, 60771)),
        ),
    ]
