# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0057_auto_20171023_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 30, 16, 23, 58, 642537)),
        ),
    ]
