# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 01:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0063_auto_20171030_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 30, 22, 11, 54, 138281)),
        ),
    ]
