# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 11:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0065_auto_20171030_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 1, 8, 42, 32, 760068)),
        ),
    ]
