# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 03:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0066_auto_20171101_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ('-data_venda',), 'verbose_name': 'venda', 'verbose_name_plural': 'vendas'},
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 16, 0, 56, 10, 882898)),
        ),
    ]
