# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 00:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0076_auto_20171116_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 16, 21, 13, 45, 4381)),
        ),
    ]
