# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 16:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0079_auto_20171116_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 17, 13, 43, 10, 928576)),
        ),
    ]
