# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 14:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0081_auto_20171118_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 18, 11, 47, 28, 891931)),
        ),
    ]
