# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0082_auto_20171118_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='pago',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 20, 14, 58, 23, 257966)),
        ),
    ]
