# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cliente', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('cnpj', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=12)),
                ('sexo', models.IntegerField(choices=[(1, 'Feminino'), (2, 'Masculino'), (3, 'Outros')])),
                ('nascimento', models.DateField()),
                ('foto', models.ImageField(default='no-image-box.png', upload_to='cliente')),
                ('estado_civil', models.IntegerField(choices=[(1, 'Solteiro'), (2, 'Casado'), (3, 'Outros')], default=1)),
                ('comanda', models.BooleanField(default=False)),
                ('status_ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('complemento', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'endereco',
                'verbose_name_plural': 'enderecos',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Endereco'),
        ),
    ]
