# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cliente', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(blank=True, max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('sexo', models.IntegerField(choices=[(1, 'Feminino'), (2, 'Masculino'), (3, 'Outros')])),
                ('nascimento', models.DateField()),
                ('estado_civil', models.IntegerField(choices=[(1, 'Solteiro'), (2, 'Casado'), (3, 'Outros')], default=1)),
                ('comanda', models.BooleanField(default=False)),
                ('status_ativo', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(blank=True, default='no-image-box.png', upload_to='cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'clientes',
                'verbose_name': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Residencial'), (2, 'Trabalho'), (3, 'Outros')])),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.IntegerField(choices=[(1, 'ACAILANDIA'), (2, 'AFONSO CUNHA'), (3, 'AGUA DOCE DO MARANHAO'), (4, 'ALCANTARA'), (5, 'ALDEIAS ALTAS'), (6, 'ALTAMIRA DO MARANHAO'), (7, 'ALTO ALEGRE DO MARANHAO'), (8, 'ALTO ALEGRE DO PINDARE'), (9, 'ALTO PARNAIBA'), (10, 'AMAPA DO MARANHAO'), (11, 'AMARANTE DO MARANHAO'), (12, 'ANAJATUBA'), (13, 'ANAPURUS'), (14, 'APICUM-ACU'), (15, 'ARAGUANA'), (16, 'ARAIOSES'), (17, 'ARAME'), (18, 'ARARI'), (19, 'AXIXA'), (20, 'BACABAL'), (21, 'BACABEIRA'), (22, 'BACURI'), (23, 'BACURITUBA'), (24, 'BALSAS'), (25, 'BARAO DE GRAJAU'), (26, 'BARRA DO CORDA'), (27, 'BARREIRINHAS'), (28, 'BELAGUA'), (29, 'BELA VISTA DO MARANHAO'), (30, 'BENEDITO LEITE'), (31, 'BEQUIMAO'), (32, 'BERNARDO DO MEARIM'), (33, 'BOA VISTA DO GURUPI'), (34, 'BOM JARDIM'), (35, 'BOM JESUS DAS SELVAS'), (36, 'BOM LUGAR'), (37, 'BREJO'), (38, 'BREJO DE AREIA'), (39, 'BURITI'), (40, 'BURITI BRAVO'), (41, 'BURITICUPU'), (42, 'BURITIRANA'), (43, 'CACHOEIRA GRANDE'), (44, 'CAJAPIO'), (45, 'CAJARI'), (46, 'CAMPESTRE DO MARANHAO'), (47, 'CANDIDO MENDES'), (48, 'CANTANHEDE'), (49, 'CAPINZAL DO NORTE'), (50, 'CAROLINA'), (51, 'CARUTAPERA'), (52, 'CAXIAS'), (53, 'CEDRAL'), (54, 'CENTRAL DO MARANHAO'), (55, 'CENTRO DO GUILHERME'), (56, 'CENTRO NOVO DO MARANHAO'), (57, 'CHAPADINHA'), (58, 'CIDELANDIA'), (59, 'CODO'), (60, 'COELHO NETO'), (61, 'COLINAS'), (62, 'CONCEICAO DO LAGO-ACU'), (63, 'COROATA'), (64, 'CURURUPU'), (65, 'DAVINOPOLIS'), (66, 'DOM PEDRO'), (67, 'DUQUE BACELAR'), (68, 'ESPERANTINOPOLIS'), (69, 'ESTREITO'), (70, 'FEIRA NOVA DO MARANHAO'), (71, 'FERNANDO FALCAO'), (72, 'FORMOSA DA SERRA NEGRA'), (73, 'FORTALEZA DOS NOGUEIRAS'), (74, 'FORTUNA'), (75, 'GODOFREDO VIANA'), (76, 'GONCALVES DIAS'), (77, 'GOVERNADOR ARCHER'), (78, 'GOVERNADOR EDISON LOBAO'), (79, 'GOVERNADOR EUGENIO BARROS'), (80, 'GOVERNADOR LUIZ ROCHA'), (81, 'GOVERNADOR NEWTON BELLO'), (82, 'GOVERNADOR NUNES FREIRE'), (83, 'GRACA ARANHA'), (84, 'GRAJAU'), (85, 'GUIMARAES'), (86, 'HUMBERTO DE CAMPOS'), (87, 'ICATU'), (88, 'IGARAPE DO MEIO'), (89, 'IGARAPE GRANDE'), (90, 'IMPERATRIZ'), (91, 'ITAIPAVA DO GRAJAU'), (92, 'ITAPECURU MIRIM'), (93, 'ITINGA DO MARANHAO'), (94, 'JATOBA'), (95, 'JENIPAPO DOS VIEIRAS'), (96, 'JOAO LISBOA'), (97, 'JOSELANDIA'), (98, 'JUNCO DO MARANHAO'), (99, 'LAGO DA PEDRA'), (100, 'LAGO DO JUNCO'), (101, 'LAGO VERDE'), (102, 'LAGOA DO MATO'), (103, 'LAGO DOS RODRIGUES'), (104, 'LAGOA GRANDE DO MARANHAO'), (105, 'LAJEADO NOVO'), (106, 'LIMA CAMPOS'), (107, 'LORETO'), (108, 'LUIS DOMINGUES'), (109, 'MAGALHAES DE ALMEIDA'), (110, 'MARACACUME'), (111, 'MARAJA DO SENA'), (112, 'MARANHAOZINHO'), (113, 'MATA ROMA'), (114, 'MATINHA'), (115, 'MATOES'), (116, 'MATOES DO NORTE'), (117, 'MILAGRES DO MARANHAO'), (118, 'MIRADOR'), (119, 'MIRANDA DO NORTE'), (120, 'MIRINZAL'), (121, 'MONCAO'), (122, 'MONTES ALTOS'), (123, 'MORROS'), (124, 'NINA RODRIGUES'), (125, 'NOVA COLINAS'), (126, 'NOVA IORQUE'), (127, 'NOVA OLINDA DO MARANHAO'), (128, 'OLHO D AGUA DAS CUNHAS'), (129, 'OLINDA NOVA DO MARANHAO'), (130, 'PACO DO LUMIAR'), (131, 'PALMEIRANDIA'), (132, 'PARAIBANO'), (133, 'PARNARAMA'), (134, 'PASSAGEM FRANCA'), (135, 'PASTOS BONS'), (136, 'PAULINO NEVES'), (137, 'PAULO RAMOS'), (138, 'PEDREIRAS'), (139, 'PEDRO DO ROSARIO'), (140, 'PENALVA'), (141, 'PERI MIRIM'), (142, 'PERITORO'), (143, 'PINDARE-MIRIM'), (144, 'PINHEIRO'), (145, 'PIO XII'), (146, 'PIRAPEMAS'), (147, 'POCAO DE PEDRAS'), (148, 'PORTO FRANCO'), (149, 'PORTO RICO DO MARANHAO'), (150, 'PRESIDENTE DUTRA'), (151, 'PRESIDENTE JUSCELINO'), (152, 'PRESIDENTE MEDICI'), (153, 'PRESIDENTE SARNEY'), (154, 'PRESIDENTE VARGAS'), (155, 'PRIMEIRA CRUZ'), (156, 'RAPOSA'), (157, 'RIACHAO'), (158, 'RIBAMAR FIQUENE'), (159, 'ROSARIO'), (160, 'SAMBAIBA'), (161, 'SANTA FILOMENA DO MARANHAO'), (162, 'SANTA HELENA'), (163, 'SANTA INES'), (164, 'SANTA LUZIA'), (165, 'SANTA LUZIA DO PARUA'), (166, 'SANTA QUITERIA DO MARANHAO'), (167, 'SANTA RITA'), (168, 'SANTANA DO MARANHAO'), (169, 'SANTO AMARO DO MARANHAO'), (170, 'SANTO ANTONIO DOS LOPES'), (171, 'SAO BENEDITO DO RIO PRETO'), (172, 'SAO BENTO'), (173, 'SAO BERNARDO'), (174, 'SAO DOMINGOS DO AZEITAO'), (175, 'SAO DOMINGOS DO MARANHAO'), (176, 'SAO FELIX DE BALSAS'), (177, 'SAO FRANCISCO DO BREJAO'), (178, 'SAO FRANCISCO DO MARANHAO'), (179, 'SAO JOAO BATISTA'), (180, 'SAO JOAO DO CARU'), (181, 'SAO JOAO DO PARAISO'), (182, 'SAO JOAO DO SOTER'), (183, 'SAO JOAO DOS PATOS'), (184, 'SAO JOSE DE RIBAMAR'), (185, 'SAO JOSE DOS BASILIOS'), (186, 'SAO LUIS'), (187, 'SAO LUIS GONZAGA DO MARANHAO'), (188, 'SAO MATEUS DO MARANHAO'), (189, 'SAO PEDRO DA AGUA BRANCA'), (190, 'SAO PEDRO DOS CRENTES'), (191, 'SAO RAIMUNDO DAS MANGABEIRAS'), (192, 'SAO RAIMUNDO DO DOCA BEZERRA'), (193, 'SAO ROBERTO'), (194, 'SAO VICENTE FERRER'), (195, 'SATUBINHA'), (196, 'SENADOR ALEXANDRE COSTA'), (197, 'SENADOR LA ROCQUE'), (198, 'SERRANO DO MARANHAO'), (199, 'SITIO NOVO'), (200, 'SUCUPIRA DO NORTE'), (201, 'SUCUPIRA DO RIACHAO'), (202, 'TASSO FRAGOSO'), (203, 'TIMBIRAS'), (204, 'TIMON'), (205, 'TRIZIDELA DO VALE'), (206, 'TUFILANDIA'), (207, 'TUNTUM'), (208, 'TURIACU'), (209, 'TURILANDIA'), (210, 'TUTOIA'), (211, 'URBANO SANTOS'), (212, 'VARGEM GRANDE'), (213, 'VIANA'), (214, 'VILA NOVA DOS MARTIRIOS'), (215, 'VITORIA DO MEARIM'), (216, 'VITORINO FREIRE'), (217, 'ZE DOCA')], default=20)),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'AC'), (2, 'AL'), (3, 'AP'), (4, 'AM'), (5, 'BA'), (6, 'CE'), (7, 'DF'), (8, 'ES'), (9, 'GO'), (10, 'MA'), (11, 'MT'), (12, 'MS'), (13, 'MG'), (14, 'PA'), (15, 'PR'), (16, 'PB'), (17, 'PE'), (18, 'PI'), (19, 'RJ'), (20, 'RN'), (21, 'RS'), (22, 'RO'), (23, 'RR'), (24, 'SC'), (25, 'SP'), (26, 'SE'), (27, 'TO')], default=10)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
            options={
                'verbose_name_plural': 'enderecos',
                'verbose_name': 'endereco',
            },
        ),
    ]
