# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-03 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comanda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
