# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('nome',), 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
    ]
