# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='no-image-box.png', upload_to='users', verbose_name='perfil'),
        ),
    ]
