# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170810_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='no-image-box.png', upload_to='users'),
        ),
    ]
