# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='funcao',
            field=models.IntegerField(choices=[(1, 'Cabelereira'), (2, 'Depiladora'), (3, 'Esteticista'), (4, 'Gerente'), (5, 'Manicure'), (6, 'Massoterapeuta'), (7, 'Nutrionista'), (8, 'Persona Trainer'), (9, 'Recepcionista')], default=None),
        ),
    ]
