# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170903_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='funcao',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
