# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='meta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
