# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_servico', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('foto', models.ImageField(blank=True, default='no-image-box.png', upload_to='servico')),
                ('status_ativo', models.BooleanField()),
                ('categoria', models.IntegerField(choices=[(1, 'Depilação'), (2, 'Estética Facial'), (3, 'Estética Corporal'), (4, 'Manicure'), (5, 'Salão')])),
            ],
            options={
                'verbose_name_plural': 'serviços',
                'verbose_name': 'servico',
            },
        ),
    ]
