# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-13 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_servico', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
                ('valor', models.FloatField()),
                ('foto', models.ImageField(blank=True, upload_to='servico')),
                ('status_ativo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'servico',
                'verbose_name_plural': 'servicos',
            },
        ),
    ]
