# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Depilação'), (2, 'Estética Facial'), (3, 'Estética Corporal'), (4, 'Manicure'), (5, 'Salão')], default=1),
            preserve_default=False,
        ),
    ]
