# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-06-30 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='foto',
            field=models.ImageField(default='media', upload_to='fotos'),
        ),
    ]
