# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-06-30 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_auto_20170630_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='foto',
            field=models.ImageField(upload_to='servico'),
        ),
    ]
