# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_auto_20170827_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='cod_servico',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
