# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_auto_20170906_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='cod_servico',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
