ESTADOS = (
    (1, "AC"),
    (2, "AL"),
    (3, "AP"),
    (4, "AM"),
    (5, "BA"),
    (6, "CE"),
    (7, "DF"),
    (8, "ES"),
    (9, "GO"),
    (10, "MA"),
    (11, "MT"),
    (12, "MS"),
    (13, "MG"),
    (14, "PA"),
    (15, "PR"),
    (16, "PB"),
    (17, "PE"),
    (18, "PI"),
    (19, "RJ"),
    (20, "RN"),
    (21, "RS"),
    (22, "RO"),
    (23, "RR"),
    (24, "SC"),
    (25, "SP"),
    (26, "SE"),
    (27, "TO"),
)
CIDADES = (
    (1, "Açailândia"),
    (2, "Afonso Cunha"),
)
TIPO = (
    (1, "Residencial"),
    (2, "Trabalho"),
    (3, "Outros"),
)
