# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_auto_20171016_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_movimentacao', models.CharField(max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('vencimento', models.DateField(verbose_name='vencimento')),
                ('tipo', models.IntegerField(choices=[(1, 'Entrada'), (2, 'Saida')])),
            ],
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo.Tipo'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
