# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='cod_movimentacao',
            field=models.CharField(max_length=10, verbose_name='Código de Movimentação'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Lançamento'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo.Tipo', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='Usuario responsável'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
