# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0002_auto_20171021_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='fonte_destino',
            field=models.CharField(default=1, max_length=20, verbose_name='Fonte/Destino'),
            preserve_default=False,
        ),
    ]
