# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 02:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0004_auto_20171022_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='fonte_destino',
            field=models.CharField(help_text='De onde veio ou para onde foi o dinheiro referente à transação.', max_length=20, verbose_name='Fonte/Destino'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsável'),
        ),
    ]
