# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0005_auto_20171022_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
