# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0006_auto_20171023_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
