# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0007_auto_20171023_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='observacao',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
