# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0010_auto_20171023_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='vencimento',
        ),
    ]
