# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0013_auto_20171030_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsável'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
