# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0014_auto_20171030_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.ForeignKey(help_text='Evento refere-se a quaisquer tipo de transação de entrada e saida de capital.', null=True, on_delete=django.db.models.deletion.CASCADE, to='fluxo.Tipo', verbose_name='Evento'),
        ),
    ]
