# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 01:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0017_auto_20171030_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Evento refere-se a quaisquer tipo de transação de entrada e saida de capital.', null=True, on_delete=django.db.models.deletion.CASCADE, to='fluxo.Tipo', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsável'),
        ),
    ]
