# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0019_movimentacao_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='link',
        ),
    ]
