# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0020_remove_movimentacao_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
