# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0021_movimentacao_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='fonte_destino',
            field=models.CharField(help_text='De onde veio ou para onde foi o dinheiro referente à transação.', max_length=50, verbose_name='Fonte/Destino'),
        ),
    ]
